services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=heroes'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=widgets'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
